project:
  type: book
  output-dir: docs

book:
  title: "nmfs-bioinf-2022"
  author: "Eric C. Anderson"
  date: "9/19/2022"
  chapters:
    - index.qmd
    - quick-unix-review.qmd
    - shell-prog.qmd
    - awk-intro.qmd
    - scripts-and-functions.qmd
    - slurm.qmd
    - sbatch.qmd
    - slurm-arrays.qmd
    - snake.qmd
  sidebar:
    logo: quarto-static/fisheries_header_logo_jul2019.png

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

